version: '3'

services:
  aes-encryption:
    image: riyadennis/aes-encryption:latest
    volumes:
      - code_volume:/aes-encryption
    ports:
      - 8082:8082
    restart: on-failure
    depends_on:
      - mongodb-container
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      PORT: ":8082"
    networks:
      - backend

  mongodb-container:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
    init: {}
    mongodb_data_container: {}
    code_volume: {}