version: '3'

services:
  aes-encryption:
    image: riyadennis/aes-encryption:latest
    volumes:
      - code_volume:/aes-encryption
    ports:
      - 8086:8086
    restart: on-failure
    depends_on:
      - mysql-development
    networks:
      - backend

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: encrypted_db
    ports:
      - "3308:3306"
    networks:
      - backend
    volumes:
      - .data/migrations/1_initialize_schema.up.sql:/docker-entrypoint-initdb.d/setup.sql
      - named_volume:/var/lib/mysql

networks:
  backend:
    driver: bridge
volumes:
    init: {}
    named_volume: {}
    code_volume: {}