version: '3'

services:
  aes-encryption:
    image: riyadennis/aes-encryption:latest
    volumes:
      - code_volume:/aes-encryption
    ports:
      - 8086:8086
    restart: on-failure
    depends_on:
      - mongodb-container
    networks:
      - backend

  mongodb-container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

networks:
  backend:
    driver: bridge
volumes:
    init: {}
    mongodb_data_container: {}
    code_volume: {}