// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ex/api/data.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	ToEncrypt            string   `protobuf:"bytes,1,opt,name=to_encrypt,json=toEncrypt,proto3" json:"to_encrypt,omitempty"`
	EncryptionId         string   `protobuf:"bytes,2,opt,name=encryption_id,json=encryptionId,proto3" json:"encryption_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetToEncrypt() string {
	if m != nil {
		return m.ToEncrypt
	}
	return ""
}

func (m *Data) GetEncryptionId() string {
	if m != nil {
		return m.EncryptionId
	}
	return ""
}

type DataRequest struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{1}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse struct {
	HttpStatus           int32    `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	EncryptionKey        string   `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{2}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

func (m *DataResponse) GetEncryptionKey() string {
	if m != nil {
		return m.EncryptionKey
	}
	return ""
}

func (m *DataResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "api.Data")
	proto.RegisterType((*DataRequest)(nil), "api.DataRequest")
	proto.RegisterType((*DataResponse)(nil), "api.DataResponse")
}

func init() { proto.RegisterFile("ex/api/data.proto", fileDescriptor_4c67c0f1791020ec) }

var fileDescriptor_4c67c0f1791020ec = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xad, 0xfd, 0x03, 0x99, 0x54, 0xb1, 0x73, 0x90, 0x22, 0x14, 0x25, 0x22, 0x78, 0x90,
	0x14, 0xea, 0xd9, 0x9b, 0x1e, 0xd4, 0x5b, 0xf2, 0x01, 0xc2, 0xd8, 0x0c, 0xb8, 0x08, 0xd9, 0x75,
	0x77, 0x2a, 0xe6, 0xdb, 0x97, 0xcc, 0x2e, 0x34, 0xc7, 0xfd, 0xbd, 0xb7, 0x6f, 0x7f, 0x2c, 0xac,
	0xf8, 0x7f, 0x4b, 0xce, 0x6c, 0x5b, 0x12, 0x2a, 0x9d, 0xb7, 0x62, 0x71, 0x4a, 0xce, 0x14, 0x1f,
	0x30, 0x7b, 0x25, 0x21, 0xdc, 0x00, 0x88, 0x6d, 0xb8, 0xdb, 0xfb, 0xde, 0xc9, 0x7a, 0x72, 0x37,
	0x79, 0xcc, 0xaa, 0x4c, 0xec, 0x5b, 0x04, 0x78, 0x0f, 0x17, 0x29, 0x33, 0xb6, 0x6b, 0x4c, 0xbb,
	0x3e, 0xd7, 0xc6, 0xf2, 0x04, 0xdf, 0xdb, 0xe2, 0x09, 0xf2, 0x61, 0xab, 0xe2, 0xdf, 0x03, 0x07,
	0xc1, 0x0d, 0xcc, 0x86, 0xd7, 0x74, 0x2c, 0xdf, 0x65, 0x25, 0x39, 0x53, 0x6a, 0xae, 0xb8, 0xe8,
	0x60, 0x19, 0xdb, 0xc1, 0xd9, 0x2e, 0x30, 0xde, 0x42, 0xfe, 0x2d, 0xe2, 0x9a, 0x20, 0x24, 0x87,
	0xa0, 0xb7, 0xe6, 0x15, 0x0c, 0xa8, 0x56, 0x82, 0x0f, 0x70, 0x39, 0x72, 0xf8, 0xe1, 0x3e, 0x49,
	0x8c, 0xcc, 0x3e, 0xb9, 0xc7, 0x6b, 0x58, 0xa4, 0x89, 0xa9, 0xc6, 0xe9, 0xb4, 0x7b, 0x89, 0x76,
	0x35, 0xfb, 0x3f, 0xb3, 0x67, 0x2c, 0x61, 0x5e, 0x8b, 0xf5, 0x8c, 0x57, 0x27, 0xb1, 0x28, 0x7e,
	0xb3, 0x1a, 0x91, 0x28, 0x57, 0x9c, 0x7d, 0x2d, 0xf4, 0xd3, 0x9e, 0x8f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xb8, 0x97, 0x9d, 0x38, 0x49, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	// unary call for now
	Store(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type dataServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataServiceClient(cc *grpc.ClientConn) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) Store(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/api.DataService/dataRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	// unary call for now
	Store(context.Context, *DataRequest) (*DataResponse, error)
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataService/dataRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Store(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "dataRequest",
			Handler:    _DataService_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex/api/data.proto",
}
