// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ex/api/data.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DataRequest struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{1}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse struct {
	HttpStatus           int32    `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	EncryptionKey        string   `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	EncryptionId         string   `protobuf:"bytes,3,opt,name=encryption_id,json=encryptionId,proto3" json:"encryption_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{2}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

func (m *DataResponse) GetEncryptionKey() string {
	if m != nil {
		return m.EncryptionKey
	}
	return ""
}

func (m *DataResponse) GetEncryptionId() string {
	if m != nil {
		return m.EncryptionId
	}
	return ""
}

type RetrieveRequest struct {
	EncryptionKey        string   `protobuf:"bytes,1,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	EncryptionId         string   `protobuf:"bytes,2,opt,name=encryption_id,json=encryptionId,proto3" json:"encryption_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveRequest) Reset()         { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()    {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{3}
}

func (m *RetrieveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRequest.Unmarshal(m, b)
}
func (m *RetrieveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRequest.Merge(m, src)
}
func (m *RetrieveRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveRequest.Size(m)
}
func (m *RetrieveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRequest proto.InternalMessageInfo

func (m *RetrieveRequest) GetEncryptionKey() string {
	if m != nil {
		return m.EncryptionKey
	}
	return ""
}

func (m *RetrieveRequest) GetEncryptionId() string {
	if m != nil {
		return m.EncryptionId
	}
	return ""
}

type RetrieveResponse struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveResponse) Reset()         { *m = RetrieveResponse{} }
func (m *RetrieveResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveResponse) ProtoMessage()    {}
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{4}
}

func (m *RetrieveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveResponse.Unmarshal(m, b)
}
func (m *RetrieveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveResponse.Merge(m, src)
}
func (m *RetrieveResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveResponse.Size(m)
}
func (m *RetrieveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveResponse proto.InternalMessageInfo

func (m *RetrieveResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "api.Data")
	proto.RegisterType((*DataRequest)(nil), "api.DataRequest")
	proto.RegisterType((*DataResponse)(nil), "api.DataResponse")
	proto.RegisterType((*RetrieveRequest)(nil), "api.RetrieveRequest")
	proto.RegisterType((*RetrieveResponse)(nil), "api.RetrieveResponse")
}

func init() { proto.RegisterFile("ex/api/data.proto", fileDescriptor_4c67c0f1791020ec) }

var fileDescriptor_4c67c0f1791020ec = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0x87, 0x4d, 0x1f, 0x6a, 0x27, 0x55, 0xdb, 0x41, 0x21, 0x14, 0xc4, 0xb2, 0x22, 0x78, 0x90,
	0x14, 0xeb, 0xc9, 0xbb, 0x17, 0xf1, 0x96, 0x9c, 0x25, 0xac, 0xcd, 0xa0, 0x8b, 0x98, 0x5d, 0x77,
	0xa7, 0xa5, 0xc1, 0x7f, 0x5e, 0xb2, 0x31, 0xa4, 0x54, 0x91, 0x1e, 0xf3, 0xe5, 0x37, 0xdf, 0x3c,
	0x16, 0xc6, 0xb4, 0x9e, 0x49, 0xa3, 0x66, 0xb9, 0x64, 0x19, 0x1b, 0xab, 0x59, 0x63, 0x57, 0x1a,
	0x25, 0xa6, 0xd0, 0x7b, 0x90, 0x2c, 0x31, 0x82, 0x83, 0x0f, 0x72, 0x4e, 0xbe, 0x52, 0x14, 0x4c,
	0x83, 0xeb, 0x41, 0xd2, 0x7c, 0x8a, 0x1b, 0x08, 0xab, 0x44, 0x42, 0x9f, 0x4b, 0x72, 0x8c, 0xe7,
	0xd0, 0xab, 0x1c, 0x3e, 0x15, 0xce, 0x07, 0xb1, 0x34, 0x2a, 0xf6, 0xff, 0x3d, 0x16, 0x5f, 0x30,
	0xac, 0xd3, 0xce, 0xe8, 0xc2, 0x11, 0x5e, 0x40, 0xf8, 0xc6, 0x6c, 0x32, 0xc7, 0x92, 0x97, 0xce,
	0x57, 0xf5, 0x13, 0xa8, 0x50, 0xea, 0x09, 0x5e, 0xc1, 0x31, 0x15, 0x0b, 0x5b, 0x1a, 0x56, 0xba,
	0xc8, 0xde, 0xa9, 0x8c, 0x3a, 0xbe, 0xff, 0x51, 0x4b, 0x9f, 0xa8, 0xc4, 0x4b, 0xd8, 0x00, 0x99,
	0xca, 0xa3, 0xae, 0x4f, 0x0d, 0x5b, 0xf8, 0x98, 0x8b, 0x67, 0x38, 0x49, 0x88, 0xad, 0xa2, 0x15,
	0x35, 0xe3, 0xfe, 0xd6, 0x07, 0x3b, 0xe9, 0x3b, 0x7f, 0xe8, 0x6f, 0x61, 0xd4, 0xea, 0x7f, 0xf6,
	0xfb, 0xff, 0x1c, 0xf3, 0x75, 0x7d, 0xbc, 0x94, 0xec, 0x4a, 0x2d, 0x08, 0x63, 0xe8, 0xa7, 0xac,
	0x2d, 0xe1, 0xa8, 0x0d, 0xd6, 0x83, 0x4e, 0xc6, 0x1b, 0xa4, 0x76, 0x8b, 0x3d, 0xbc, 0x87, 0xc3,
	0xa6, 0x23, 0x9e, 0xfa, 0xc0, 0xd6, 0x7e, 0x93, 0xb3, 0x2d, 0xda, 0x94, 0xbe, 0xec, 0xfb, 0x47,
	0xbe, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x0d, 0xc6, 0x9a, 0xf9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	// unary call for now
	Store(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) Store(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/api.DataService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, "/api.DataService/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	// unary call for now
	Store(context.Context, *DataRequest) (*DataResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) Store(ctx context.Context, req *DataRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedDataServiceServer) Retrieve(ctx context.Context, req *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Store(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataService/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _DataService_Store_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _DataService_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex/api/data.proto",
}
