// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ex/api/data.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	ToEncrypt            string   `protobuf:"bytes,1,opt,name=to_encrypt,json=toEncrypt,proto3" json:"to_encrypt,omitempty"`
	EncryptionId         string   `protobuf:"bytes,2,opt,name=encryption_id,json=encryptionId,proto3" json:"encryption_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetToEncrypt() string {
	if m != nil {
		return m.ToEncrypt
	}
	return ""
}

func (m *Data) GetEncryptionId() string {
	if m != nil {
		return m.EncryptionId
	}
	return ""
}

type DataRequest struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{1}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse struct {
	HttpStatus           int32    `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	EncryptionKey        string   `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c67c0f1791020ec, []int{2}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

func (m *DataResponse) GetEncryptionKey() string {
	if m != nil {
		return m.EncryptionKey
	}
	return ""
}

func (m *DataResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "api.Data")
	proto.RegisterType((*DataRequest)(nil), "api.DataRequest")
	proto.RegisterType((*DataResponse)(nil), "api.DataResponse")
}

func init() { proto.RegisterFile("ex/api/data.proto", fileDescriptor_4c67c0f1791020ec) }

var fileDescriptor_4c67c0f1791020ec = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x9d, 0xdd, 0x06, 0x3d, 0x9d, 0xe2, 0xce, 0x85, 0x0c, 0x61, 0x28, 0x15, 0xc1, 0x0b,
	0xe9, 0x60, 0xe2, 0x03, 0x08, 0x7a, 0xa1, 0xde, 0x75, 0x0f, 0x50, 0x8e, 0xf6, 0x80, 0x41, 0x48,
	0x62, 0x73, 0x06, 0xf6, 0xed, 0xa5, 0x27, 0x81, 0xf6, 0x32, 0xdf, 0xff, 0xe7, 0xcf, 0x47, 0x60,
	0xcd, 0x7f, 0x3b, 0xf2, 0x66, 0xd7, 0x92, 0x50, 0xe5, 0x3b, 0x27, 0x0e, 0x33, 0xf2, 0xa6, 0x7c,
	0x87, 0xf9, 0x0b, 0x09, 0xe1, 0x16, 0x40, 0x5c, 0xc3, 0xf6, 0xab, 0xeb, 0xbd, 0x6c, 0x66, 0x37,
	0xb3, 0xfb, 0xbc, 0xce, 0xc5, 0xbd, 0x46, 0x80, 0xb7, 0x70, 0x96, 0x32, 0xe3, 0x6c, 0x63, 0xda,
	0xcd, 0xa9, 0x36, 0x56, 0x23, 0x7c, 0x6b, 0xcb, 0x07, 0x28, 0x86, 0xad, 0x9a, 0x7f, 0x8f, 0x1c,
	0x04, 0xb7, 0x30, 0x1f, 0x5e, 0xd3, 0xb1, 0x62, 0x9f, 0x57, 0xe4, 0x4d, 0xa5, 0xb9, 0xe2, 0xd2,
	0xc2, 0x2a, 0xb6, 0x83, 0x77, 0x36, 0x30, 0x5e, 0x43, 0xf1, 0x2d, 0xe2, 0x9b, 0x20, 0x24, 0xc7,
	0xa0, 0xb7, 0x16, 0x35, 0x0c, 0xe8, 0xa0, 0x04, 0xef, 0xe0, 0x7c, 0xe2, 0xf0, 0xc3, 0x7d, 0x92,
	0x98, 0x98, 0x7d, 0x70, 0x8f, 0x97, 0xb0, 0x4c, 0x13, 0x99, 0xc6, 0xe9, 0xb4, 0x7f, 0x82, 0xec,
	0x99, 0x03, 0x56, 0xb0, 0x38, 0x88, 0xeb, 0x18, 0x2f, 0x46, 0xa1, 0x28, 0x7c, 0xb5, 0x9e, 0x90,
	0x28, 0x55, 0x9e, 0x7c, 0x2e, 0xf5, 0xb3, 0x1e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xb9,
	0xee, 0x89, 0x41, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AesClient is the client API for Aes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AesClient interface {
	// unary call for now
	Store(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type aesClient struct {
	cc grpc.ClientConnInterface
}

func NewAesClient(cc grpc.ClientConnInterface) AesClient {
	return &aesClient{cc}
}

func (c *aesClient) Store(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/api.Aes/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AesServer is the server API for Aes service.
type AesServer interface {
	// unary call for now
	Store(context.Context, *DataRequest) (*DataResponse, error)
}

// UnimplementedAesServer can be embedded to have forward compatible implementations.
type UnimplementedAesServer struct {
}

func (*UnimplementedAesServer) Store(ctx context.Context, req *DataRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}

func RegisterAesServer(s *grpc.Server, srv AesServer) {
	s.RegisterService(&_Aes_serviceDesc, srv)
}

func _Aes_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AesServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Aes/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AesServer).Store(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Aes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Aes",
	HandlerType: (*AesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Aes_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex/api/data.proto",
}
